export const EDIT_SUCCES = 'EDIT_SUCCES';
export const EDIT_FAIL = 'EDIT_FAIL';

export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const CREATE_TEXT = 'CREATE_TEXT';

export const GET_PERMISION = 'GET_PERMISION';
export const ADD_PERMISION = 'ADD_PERMISION';
export const DELETE_PERMISION = 'DELETE_PERMISION';

export const GET_DOCUMENT_VERSION = 'GET_DOCUMENT_VERSION';
export const GET_DOCUMENT_VERSION_ByID = 'GET_DOCUMENT_VERSION_ByID';
export const ADD_DOCUMENT_VERSION = 'ADD_DOCUMENT_VERSION';
export const GET_DOCUMENT_VERSION_CONTENT = 'GET_DOCUMENT_VERSION_CONTENT';

export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const GET_NOTIFICATION_NUMBER = 'GET_NOTIFICATION_NUMBER';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_TOPERMISONS = 'GET_USERS_TOPERMISONS';
export const GET_USER_AUTH = 'GET_USER_AUTH';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCES = 'LOGOUT_SUCCES';
export const REGISTER_SUCCES = 'REGISTER_SUCCES';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';